# Site settings
title: opengers
email: zijian1012#gmail.com
description: > # this means to ignore newlines until "baseurl:"
  kvm,python,docker,devops
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://opengers.github.io" # the base hostname & protocol for your site
#twitter_username: stevenvmiller
github_username:  opengers

name: opengers

# Build settings
markdown: kramdown
kramdown:
  input:         GFM
  auto_ids:      true
  extensions: ["autolink", "tables"]

job.title: "DevOps"
excerpt_separator: "<!--more-->"

gems:
  - jekyll-sitemap

plugins:
  - jekyll-feed
  - jekyll-seo-tag
