# Site settings
title: opengers
email: zijian1012#gmail.com
description: > # this means to ignore newlines until "baseurl:"
  kvm,python,docker,devops
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.isjian.com" # the base hostname & protocol for your site
#twitter_username: stevenvmiller
github_username:  opengers

# Build settings
#markdown: kramdown
#kramdown:
# input:         GFM
#  #auto_ids:      true
#  extensions: ["autolink", "tables"]

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions:
    - fenced_code_blocks
    - no_intra_emphasis
    - strikethrough
    - autolink
    - tables

#markdown: redcarpet
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

#redcarpet:
#extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
# Other options
# permalink: blog/:year/:month/:title/

job.title: "DevOps"
excerpt_separator: "<!--more-->"

# SEO stuff
#google_author: "https://plus.google.com/u/0/110288225974212014913"
#google_site_verification: "nfd8hkZSc3GmIivrLCudAdTq5m1kI0Ao7P1UyIt9z5Q"
#bing_webmastertools_id: "E24D33E8D53D5730794478CB209F15E5"

gems:
  - jekyll-sitemap
